### PR TITLE
docs: add npm badge to readme

### PR DESCRIPTION
**Pull request by ChristianMurphy**
[NPM Version](https://www.npmjs.com/package/gradle-to-js)

### CODE REVIEW

**Comment by karllindmark** [comment]
That's a nice touch - thanks! 👍

**Comment by ChristianMurphy** [comment]
Thanks @karllindmark!
Any chance the past few commits could be included in a new release?

**Comment by karllindmark** [comment]
Hey Christian!

Hoping to put out a release this weekend - need to get that machinery
sorted again. Probably in the cloud... 😊

Med vänliga hälsningar,
Karl Lindmark

**Comment by karllindmark** [comment]
Hey @ChristianMurphy, 1.2.0 just rolled out. Thanks once again!

**Pull request merged**
