### PR TITLE
Updates loadash.merge to latest version

### PR DESCRIPTION
**Pull request by owenniblock**
### Motivation

We'd like this released so we can update our dependency in another project :)

`npm test` runs all pass.

### CODE REVIEW

**Comment by karllindmark** [comment]
Hi Owen!

Thank you for your contribution!

One minor thing - could you please adjust the commit slightly and freeze
(is that the correct term?) the version?

Best regards,
Karl Lindmark

**Comment by owenniblock** [comment]
Done! :)

**Comment by karllindmark** [comment]
Thanks a bunch - will merge it shortly!

Now that my vacation has started I might have time to squeeze #25 in too
before releasing. 😀

**Comment by owenniblock** [comment]
Thanks @karllindmark - if there's any chance of a quick release we'd really appreciate it (the update is due to a vulnerability in lodash that was announced recently so we're trying to get all our deps updated)!

**Comment by owenniblock** [comment]
Just for completeness :) https://github.com/lodash/lodash/issues/4348

**Comment by karllindmark** [comment]
Done deal, I just put up 2.0.0 (new major version due to me playing around with `\r` and the `plugins` closure) - shouldn't be noticable unless you actually relied on the previous (non-)handling of `plugins`, but if that's the case...  then you're probably going to be a lot happier anyways. :-)

**Comment by owenniblock** [comment]
Amazing! Thanks :)

**Pull request merged**
